/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export const recommended = {
  rules: {
    'require-image-alt': 'warn',
    'promote-semantic-elements-for-accessibility': 'warn',
  },
};
