/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
import { recommended } from './configs/recommended';
import exampleRule from './rules/example-rule'
import requireImgAlt from "./rules/require-img-alt";

export const configs = {
    recommended
};

export const rules = {
    'example-rule': exampleRule,
    'require-img-alt': requireImgAlt,
};
