name: Test Integration
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g pnpm @antfu/ni

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint:ts

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build
