name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install yarn

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn run lint
      - name: Test
        run: yarn run test
        env:
          CI: true

      - name: Build
        run: yarn run build
